---
- name: create coredns config directory
  file:
    path: /opt/coredns
    state: directory
    owner: root
    group: root
    mode: 775
  tags: dns

- name: create coredns config
  copy:
    dest: /opt/coredns/Corefile
    owner: root
    group: root
    mode: 644
    content: |
      .:53 {
        bind 172.16.3.2
        forward . 192.168.1.1
      }
  tags: dns

- name: open firewall for DNS - (port 53)
  firewalld:
    zone: public
    service: dns
    permanent: yes
    immediate: yes
    state: enabled
  tags: dns

- name: start coredns container
  containers.podman.podman_container:
    name: coredns
    state: started
    detach: yes
    network: host
    restart_policy: always
    volumes:
    - /opt/coredns/Corefile:/Corefile
    ports:
    - 172.16.3.2:53:53
    image: coredns/coredns
  tags: dns

