# ============================================================================
# Network interfaces and bridges
# ============================================================================

- name: Add resolver to global dns
  lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: "^[Resolve]"
    regexp: "^#?DNS="
    line: DNS=192.168.1.1
  notify: restart resolved
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == 8  
  
- name: Add search domains to global dns
  lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: "^[Resolve]"
    regexp: "^#?Domains="
    line: Domains=lamourine.org
  notify: restart resolved
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == 8  

# enp4s0 - down 00:e0:4c:67:92:36
# enp5s0 - r1p2 00:e0:4c:67:92:37
# enp8s0 - r2p1 00:e0:4c:87:00:57
# enp9s0 - r2p2 00:e0:4c:87:00:58

- name: Add bridge interfaces
  template:
    src: ifcfg-br-xxx.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-br-{{ item.key }}"
    backup: yes
  with_dict: "{{ bridges }}"
  notify: restart network  
    
- name: Add bridge devices
  template:
    src: ifcfg-xxx.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.value.device }}"
    backup: yes
  with_dict: "{{ bridges }}"
  notify: restart network  
